pipeline {

    agent any


    environment {

        IMAGE_NAME = "localhost:8083/mr/spring-petclinic"

    }


    stages {


        stage('Checkstyle') {

            steps {

                dir('Spring-Petclinic-Assignments/spring-petclinic') {

                    sh '''
                    ./mvnw checkstyle:checkstyle || true
                    '''

                }

            }


            post {

                always {

                    archiveArtifacts(
                        artifacts: '**/target/checkstyle-result.xml',
                        allowEmptyArchive: true
                    )

                }

            }

        }



        stage('Test') {

            steps {

                dir('Spring-Petclinic-Assignments/spring-petclinic') {

                    sh './mvnw test'

                }

            }

        }



        stage('Build') {

            steps {

                dir('Spring-Petclinic-Assignments/spring-petclinic') {

                    sh './mvnw package -DskipTests'

                }

            }

        }



        stage('Docker Build') {


            steps {


                dir('Spring-Petclinic-Assignments/spring-petclinic') {


                    script {


                        def commitId = sh(
                            script: "git rev-parse --short HEAD",
                            returnStdout: true
                        ).trim()



                        sh """
                        docker build \
                        -f Dockerfile.multi \
                        -t ${IMAGE_NAME}:${commitId} .
                        """


                        env.IMAGE_TAG = commitId

                    }

                }

            }

        }



        stage('Push Docker Image') {


            steps {


                sh """

                docker login localhost:8083 \
                -u admin \
                -p \$(cat /nexus-password)

                docker push ${IMAGE_NAME}:${IMAGE_TAG}

                """

            }

        }


    }


    post {


        success {

            echo "Pipeline completed successfully"

        }


        failure {

            echo "Pipeline failed"

        }

    }

}