pipeline {

    agent any


    environment {

        MAIN_NEXUS = "localhost:8082"
        MR_NEXUS = "localhost:8084"

        IMAGE_NAME = "spring-petclinic"

    }


    stages {


        stage('Checkout') {

            steps {

                checkout scm

            }

        }



        stage('Checkstyle') {


            when {

                not {

                    branch 'main'

                }

            }


            steps {


                dir('Spring-Petclinic-Assignments/spring-petclinic') {


                    sh '''

                    ./mvnw checkstyle:checkstyle

                    '''

                }

            }


            post {


                always {


                    archiveArtifacts(
                        artifacts: '**/target/checkstyle-result.xml',
                        allowEmptyArchive: true
                    )


                }

            }

        }




        stage('Test') {


            when {

                not {

                    branch 'main'

                }

            }


            steps {


                dir('Spring-Petclinic-Assignments/spring-petclinic') {


                    sh './mvnw test'


                }

            }

        }





        stage('Build') {


            when {

                not {

                    branch 'main'

                }

            }


            steps {


                dir('Spring-Petclinic-Assignments/spring-petclinic') {


                    sh './mvnw package -DskipTests'


                }

            }

        }





        stage('Docker Build') {


            steps {


                dir('Spring-Petclinic-Assignments/spring-petclinic') {


                    script {


                        def commitId = sh(
                            script: "git rev-parse --short HEAD",
                            returnStdout: true
                        ).trim()



                        if(env.BRANCH_NAME == "main") {


                            env.DOCKER_IMAGE =
                            "${MAIN_NEXUS}/${IMAGE_NAME}:latest"


                        }
                        else {


                            env.DOCKER_IMAGE =
                            "${MR_NEXUS}/${IMAGE_NAME}:${commitId}"


                        }



                        sh """

                        docker build \
                        -f Dockerfile.multi \
                        -t ${DOCKER_IMAGE} .


                        """


                    }

                }

            }

        }




stage('Docker Push') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'nexus-creds',
                usernameVariable: 'USERNAME',
                passwordVariable: 'PASSWORD'
            )
        ]) {
            script {
                def nexusRegistry = env.BRANCH_NAME == "main" ? env.MAIN_NEXUS : env.MR_NEXUS

                sh """
                    echo \$PASSWORD | docker login ${nexusRegistry} \
                    -u \$USERNAME \
                    --password-stdin

                    docker push ${env.DOCKER_IMAGE}
                """
            }
        }
    }
}



    }




    post {


        success {

            echo "Pipeline completed successfully"

        }


        failure {

            echo "Pipeline failed"

        }


    }


}